// /app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Lordicon Script */}
        <script src="https://cdn.lordicon.com/lordicon.js"></script>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
